name: Create Preview Image

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Packages
        run: |
          sudo apt-get install imagemagick
          
      - name: Change ImageMagick policy to allow pdf to png conversion.
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
                    
      - name: Convert Image
        run: |
          sudo magick -density 150 resume.pdf -quality 90 resume.jpg
          
      - name: Commit files
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "compile resume"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
