name: Create Preview Image

on:

  workflow_run:
    workflows: ["Compile LaTeX"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Packages
        run: |
          sudo apt-get install imagemagick ghostscript
          
      - name: Change ImageMagick policy to allow pdf to png conversion.
        run: |
          sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
                    
      - name: Convert Image
        run: |
          sudo convert -density 3000 resume.pdf -quality 100 resume.jpg
          
      - name: Commit files
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "generate preview and add resume.jpg" --allow-empty
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
