name: Lint Typst

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive
    
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: typstyle
          
      - name: Lint Typst
        run: |
          cd typst
          typstyle rajeev_atla_resume.typ resume.typ --inplace --indent-width 4 --verbose --timing
          cd ..
      
      - name: Commit Files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Lint Typst"
      
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
          
