name: Lint LaTeX

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 * * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Packages
        run: |
          sudo apt-get install chktex
                    
      - name: Lint
        run: |
          chktex resume.tex -d 16
          chktex rajeevresume.sty -d 16
